# Generated by Django 5.1 on 2024-11-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imgProduto',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
